DROP TABLE IF EXISTS PRICES;
DROP TABLE IF EXISTS BRANDS;
DROP TABLE IF EXISTS PRICES_LIST;
DROP TABLE IF EXISTS PRODUCTS;

CREATE TABLE BRANDS (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);

CREATE TABLE PRICES_LIST (
    ID INT PRIMARY KEY,
    DESCRIPTION VARCHAR(50) NOT NULL
);

CREATE TABLE PRODUCTS (
    ID NUMERIC(6) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);

CREATE TABLE PRICES (
    ID INT PRIMARY KEY,
    BRAND_ID INT NOT NULL REFERENCES BRANDS(ID),
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE_LIST_ID INT NOT NULL REFERENCES PRICES_LIST(ID),
    PRODUCT_ID VARCHAR(10) NOT NULL REFERENCES PRODUCTS(ID),
    PRIORITY INT NOT NULL,
    PRICE DOUBLE NOT NULL,
    CURR VARCHAR(10) NOT NULL
);
